### ISSUE TITLE
Fall 2025 To-Do

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/molb-7950#37]
## Before class starts

- [ ] Set up Posit Cloud (Aug 1 start)
- [ ] Send welcome e-mail (includes/_welcome-email.qmd) (Aug 15)

## After class ends

- [ ] Submit final grades
- [ ] Submit a room request for next Fall (AHSB 2201)
